homeapp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home_page,name='home_page'),
    path('post/',views.create_post,name='post_page'),
    path('blog_view/',views.blog_view,name='blog_view'),
    
    
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tukiz/urls.py
from django.contrib import admin, sitemaps
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from homeapp import sitemaps
from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import url
# from django.views.static import serve
sitemaps = {
    'static':sitemaps.StaticViewSitemap,
    'blog_view':sitemaps.blog_view,
    'login':sitemaps.login,
    'logout':sitemaps.logout,
    'register':sitemaps.register


}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
    path('',include('homeapp.urls')),
    path('',include('user.urls')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
urlpatterns=[

    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('register/',register,name='register'),
]

homeapp/models.py
from django.db import models

# Create your models here.

user/models.py
#from typing_extensions import Required
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from django.db.models.fields import CharField
from django.db.models.fields.files import FileField
from django.db.models.fields.related import OneToOneField
from PIL import Image
# Create your models here.
class post(models.Model):

    user=models.ForeignKey(User,on_delete=CASCADE)
    title = models.CharField(max_length=250,default="No title")
    body=models.TextField(blank=True)
    meta_body=models.CharField(max_length=90,default="none",blank=False)
    image = models.ImageField(blank=True ,default='none.jpg')
    def __str__(self) -> str:
        return f'{self.user}and post no{self.id}'
    # def save(self):
    #     super().save()
    #     img = Image.open(self.image.path)
    #     if img.height > 150 or img.width > 300:
    #         output_size=(100,100)
    #         img.resize(output_size)
    #         img.save(self.image.path)


class postphotos(models.Model):
    user = models.ForeignKey(post,on_delete=CASCADE)
    image = models.ImageField(blank=True ,default='none.jpg')
    def __str__(self) -> str:
        return f'{self.user}and post no{self.id}'


class postbody(models.Model):
    user = models.ForeignKey(post,on_delete=CASCADE)
    body = models.TextField(default="")
    def __str__(self) -> str:
        return f'{self.user}and post no{self.id}'
class postfile(models.Model):
    user = models.ForeignKey(post,on_delete=CASCADE)
    image = models.ImageField(blank=True ,default='none.jpg')
    def __str__(self) -> str:
        return f'{self.user}and post no{self.id}'




class comment(models.Model):
    key=models.ForeignKey(post,on_delete=CASCADE)
    comment_body=models.TextField()
    comment_body_sys=models.TextField(default="")
    user = models.CharField(max_length=4,default="None")
    file=models.FileField(default='media/none.jpg',blank=True)
    is_auth = models.BooleanField(blank=False,default=False)
    def __str__(self) -> str:
        return f'post id::{self.key.id}'
    


class profile(models.Model):
    user=OneToOneField(User,on_delete=CASCADE)
    profile_image=FileField(default='media/none.jpg',blank=True)
    nick_name=CharField(default='none',max_length=50,blank=True)
    def __str__(self) -> str:
        return f'{self.user.username}...profile {self.user.id}'

homeapp/views.py
from user.models import post
from django.http import request
from django.shortcuts import render,redirect
from django.contrib.auth.models import *
from .additionals import *
from django.core.files.storage import FileSystemStorage
from user.models import *
import json
# Create your views here.
def home_page(request):
    post_data=post.objects.all()
    context={'posts': post_data}#all the post from data base
    return render(request,'homeapp/index.html',context)



def create_post(request):
    if request.user.is_authenticated:
                if request.method=='POST':                  
                    create_posts(request)
                    print(request.FILES)
                    return redirect('home_page')
        
    else:
        
        return redirect('login')
    return render(request,'homeapp/post.html',None)



def blog_view(request):
    get_request_data=request.GET
    print(get_request_data)
    data = get_all_data(request)#INITIAL PROJECT DATA
    body = process_post_body(data['post'].body)#INITIAL DATA
    if request.method=='POST' and request.POST.get('class') == "comment":
        make_comment(request,data)
    data = get_all_data(request)
    body = process_post_body(data['post'].body)
    return render(request,'homeapp/blog_view.html',{'data':data,'body':body})

user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
# Create your views here.






#REGISTER
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!\n Please Login to your account')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'user/register.html', {'form': form})

homeapp/templates/homeapp/blog_view.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta property="fb:app_id" content="488532302229028" />
    <meta property="og:url" content="https://tuke.pythonanywhere.com/blog_view/?post_id={{data.post.id}}&class=blog_view" />
    <meta property="og:image" content="https://tuke.pythonanywhere.com{{data.post.image.url}}" />

    <meta name="google-site-verification" content="WrVcwoD2s1X47xe8pKobr7K4Qr6lda8IsvBDAeFyIvg" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <meta name="keywords" content="{{data.post.title}}"/>
    <meta name="description" content="{{data.post.meta_body}}">


    <meta property="og:title" content="{{data.post.title}}" />
    <meta property="og:url" content="https://tuke.pythonanywhere.com"/>
    <meta property="og:description" content="{{data.post.meta_body}}"/>

    <meta property="og:type" content="website"/>

    <link rel="stylesheet" href="{%static 'homeapp/blog_view.css'%}">
    <script src="https://kit.fontawesome.com/ee1e6a0caa.js" crossorigin="anonymous"></script>
    <title>{{data.post.title}}</title>
    <script src="{%static 'homeapp/responsive.js'%}"></script>
    <script type="text/javascript">
          function showcomment(){
              var comment = document.getElementById('showmore');
              comment.style.display='block';
              buttonshowmore.style.display = 'none';
          }              
    </script>
</head>
<body>
    
    <header>
        <nav class="navlist">
            <div class="logo"><p style="color: rgb(255, 255, 255); display: inline;">  TU</p>
               <sub>KIZ</sub>
            </div>
            <div class="list">
                <li><a href="{%url 'home_page'%}">Home</a></li>
                
                <li><a href="{%url 'post_page'%}">Create post</a></li>
                {%if not user.is_authenticated%}
                <li><a href="{%url 'register'%}">SignUp</a></li>
                {%endif%}
            </div>
            <div class="log">
                <ul class="loglist">
                    
                    <li><a href="{%url 'post_page'%}">Create post</a></li>
                    <li>F&Q</li>
                    {%if not user.is_authenticated%}
                    <li><a href="{%url 'login'%}">LogIn</a></li>
                    {%else%}
                    <li id="logout"><a href="{%url 'logout'%}" style="text-decoration: none; color: red; font-weight: bold;">LogOut</a></li>
                    {%endif%}
                </ul>
            </div>
            <div class="bars">
               <button onclick="show_bar_item()" style="border:none;background-color: transparent;"><i class="fas fa-bars"></i></button> 
               
               <div id='sbar'>
                    <div class="secondarylist">
                        <button onclick="show_bar_item()" style="border:none;background-color: transparent;">
                            <i class="fas fa-times" style="color: red;font-size: 30pt;"></i>
                        </button>
                        <div class="slist">
                           <ul>
                            <li class="a" style="margin-top: 0;"><a href="{%url 'logout'%}" >Logout</a></li>
                            <li class="a"><a href="{%url 'home_page'%}">Home</a></li>
                            <li class="a"><a href="{%url 'post_page'%}">Create post</a></li>
                            <li><a href="">About us</a></li>
                            <li><a href="{%url 'login'%}">Login</a></li>
                            <li><a href="">F&Q</a></li>
                            
                           </ul>
                        </div>
                    </div>
                </div>
               
               
            </div>
            


        </nav>
    </header>
    <div class="getstarted" >
        
        <a href="" style="font-family:cursive;font-size: 10pt;text-decoration:none;background-color:transparent;color: black;font-weight: bold;background: linear-gradient(40deg, #b2d8d6 10%, rgba(0, 240, 169, 0.978496) 86%);border-radius: 8px;padding: 2px;margin: 5px;position: relative;top:0.2cm;"> 
            Get started</a>
    </div>


    <div class="sidenav1">

    </div>
      <div class="sidenav2">
          <p><a href="">Home</a></p>
          <br>
      </div>


      <div class="showcomment" style="z-index: 10;">
        <button onclick="show_comment()">
            <i class="fas fa-comment"></i>
        </button>
        
      </div>

      <div class="comment" id="comment">
       
        <div class="postcomment">
            
            <form action="" method="POST">
                {%csrf_token%}
                <input type="text" id="PC" name='body' placeholder="  ENTER COMMENT">
                <input type="hidden" id="PC" name='class' value="comment">
                <input type="hidden" id="PC" name='data' value="{{data.post.user.id}}">
                <button type="submit"><i class="fas fa-location-arrow"></i></button>
            </form>
        </div>       
              
        <div class="close"style=""> 
            <button onclick="show_comment()">
             <i class="fas fa-times" style="color: red;font-size: 30pt; "></i>
            </button>
         </div> 
        {% for i in data.comments%}
        
        
        {%if not  i.comment.is_auth%}
        <div class="visitor">
            <div class="profileimage">
                <img src="{{i.auth.profile.profile_image.url}}" alt="{{i.user}}">
            </div>
            <div class="commentbody">
                {{i.comment.comment_body}} 
            </div>
        </div>
        {%endif%}
        {%if i.comment.is_auth%}
        <div class="author">
            <div class="profileimage">
                <img src="{{i.auth.profile.profile_image.url}}" alt="{{i.user}}">
            </div>
            <div class="commentbody">
                {{i.comment.comment_body}}
                <!-- <div class="hide">
                   
                    <button class="" onclick="showcomment()" id='buttonshowmore' style="background-color:rgba(255, 255, 255, 0.493);border:none;cursor:pointer;">showmore....</button>
                <p class="showmore" id ='showmore'>

                molestias illum commodi quidem impedit architecto suscipit possimus praesentium ab. Numquam veniam id suscipit assumenda. Perspiciatis quaerat tenetur, corporis ipsum labore nesciunt.
                </p>
                </div> -->
            </div> 
        </div>
        {%endif%}
        {%endfor%}

      </div>
      
    <div class="bgimage" >      <!-- image -->     </div>
   <div style="display: flex;justify-content: center;"><div class="title">
        {{data.post.title}}
    </div></div>
    <div class="content">
        {%for i in body%}
       <div class="body">
            <p>
                
                
                
                {%if i.text%}
                {% autoescape off %}
                <pre style="white-space: pre-wrap;       /* Since CSS 2.1 */
                white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
                white-space: -pre-wrap;      /* Opera 4-6 */
                white-space: -o-pre-wrap;    /* Opera 7 */
                word-wrap: break-word; font-family: cursive,sans-serif; font-size: 1rem;">
                    {{i.content.body|linebreaks}}
                </pre>
              
              {% endautoescape  %}
                {%endif%}
                
                {%if i.image%}
                
                <div class="image">
                    

                  <a href="{{i.url.image.url}}">  <img src="{{i.url.image.url}}" alt="{{i.url.image.url}}"></a>
                </div>
                {%endif%}
            </p> 

        </div>
        {%endfor%}
    </div>

  

</body>
</html>

homeapp/templates/homeapp/htm/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="home.css">
    <title>Document</title>
</head>
<body>

   

<form action="" method="POST" enctype="multipart/form-data"  >
       
        
        <div class="title">
            <textarea cols=40 rows="2"  aria-valuenow="Title" name="title" id ="title" placeholder="ENTER YOUR TITLE"></textarea>
        </div>
        <br>
        <div class="body">
            <textarea cols=60 rows="20"  aria-valuenow="write and express" name="body" id="body" placeholder="Express your feel you can use html syntaxs"></textarea>
        
            <div class="input">
                <input type="file" id='id_image' name='image0' /> 
                <input type="file" id='id_image' name='image1' />
                <input type="file" id='id_image' name='image2' /> 
                <input type="file" id='id_image' name='image3' />
                <input type="file" id='id_image' name='image4' /> 
                <input type="file" id='id_image' name='image5' />
                <input type="file" id='id_image' name='image6' /> 
                <input type="file" id='id_image' name='image7' />
                <input type="file" id='id_image' name='image8' /> 
                <input type="file" id='id_image' name='image9' />
                <input type="file" id='id_image' name='image10' /> 
                <input type="file" id='id_image' name='image11' />
                <input type="file" id='id_image' name='image12' /> 
                <input type="file" id='id_image' name='image13' />
                <input type="file" id='id_image' name='image14' /> 
                <input type="file" id='id_image' name='image15' />
                <input type="file" id='id_image' name='image16' />
                <input type="file" id='id_image' name='image17' />
                <input type="file" id='id_image' name='image18' /> 
                <input type="file" id='id_image' name='image19' />
                <input type="file" id='id_image' name='image20' /> 
                <input type="file" id='id_image' name='image21' />
                <input type="file" id='id_image' name='image22' /> 
                <input type="file" id='id_image' name='image23' />
                <input type="file" id='id_image' name='image24' /> 
                <input type="file" id='id_image' name='image25' />
                <input type="file" id='id_image' name='image26' /> 
                <input type="file" id='id_image' name='image27' />
                <input type="file" id='id_image' name='image28' /> 
                <input type="file" id='id_image' name='image29' />
                <input type="file" id='id_image' name='image30' /> 
                <input type="file" id='id_image' name='image31' />
                <input type="file" id='id_image' name='image32' /> 
                <input type="file" id='id_image' name='image33' />
                <input type="file" id='id_image' name='image34' />
                <input type="file" id='id_image' name='image35' />
            </div>
        
        

        </div>

       <br><h2>Insert a image</h2><br>
        
    
        <br><br><br><br><br>
   </form>

</body>
</html>

homeapp/templates/homeapp/post.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'homeapp/post.css'%}">
    <script src="{%static 'homeapp/responsive.js'%}"></script>
    <title>Create Post</title>
</head>
<body>
    
    <div class="caption">
        <i>Create New Post</i>
    </div>
    <div class="DecorateText">
                 
        Decorate Text:
        <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="button" id='italic' onclick="bold('i')"><u>i</u></button>
        <button type = "button" id='bold' onclick="bold('b')"><u>B</u></button>
    </div>
    <div class="container">
        <form action="" method="POST" enctype="multipart/form-data" >
            {%csrf_token%}
             <div><input type="text" name="title" placeholder="   Enter Titel" required></div>
             
              

                
                <div>
                <textarea name="body" id="body_textarea" cols="80" rows="17" placeholder="Enter your content ">
              

              </textarea>
              </div>


            <div class="input">
                <div><button type="button" onclick="add_image('0')">add</button><input type="file" id='id_image' name='image0' /> </div>
                <div><button type="button" onclick="add_image('1')">add</button><input type="file" id='id_image' name='image1' /></div>
                <div><button type="button" onclick="add_image('2')">add</button><input type="file" id='id_image' name='image2' /> </div>
                <div><button type="button" onclick="add_image('3')">add</button><input type="file" id='id_image' name='image3' /></div>
                <div><button type="button" onclick="add_image('4')">add</button><input type="file" id='id_image' name='image4' /> </div>
                <div><button type="button" onclick="add_image('5')">add</button><input type="file" id='id_image' name='image5' /></div>
                <div><button type="button" onclick="add_image('6')">add</button><input type="file" id='id_image' name='image6' /></div> 
                <div><button type="button" onclick="add_image('7')">add</button><input type="file" id='id_image' name='image7' /></div>
                <div><button type="button" onclick="add_image('8')">add</button><input type="file" id='id_image' name='image8' /> </div>
                <div><button type="button" onclick="add_image('9')">add</button><input type="file" id='id_image' name='image9' /></div>
                <div><button type="button" onclick="add_image('10')">add</button><input type="file" id='id_image' name='image10' /> </div>
                <div><button type="button" onclick="add_image('11')">add</button><input type="file" id='id_image' name='image11' /> </div>
                <div><button type="button" onclick="add_image('12')">add</button><input type="file" id='id_image' name='image12' /> </div> 
                <div><button type="button" onclick="add_image('13')">add</button><input type="file" id='id_image' name='image13' /></div>
                <div><button type="button" onclick="add_image('14')">add</button><input type="file" id='id_image' name='image14' /></div> 
                <div><button type="button" onclick="add_image('15')">add</button><input type="file" id='id_image' name='image15' /></div>
                <div><button type="button" onclick="add_image('16')">add</button><input type="file" id='id_image' name='image16' /></div>
                <div><button type="button" onclick="add_image('17')">add</button><input type="file" id='id_image' name='image17' /></div>
                <div><button type="button" onclick="add_image('18')">add</button><input type="file" id='id_image' name='image18' /></div> 
                <div><button type="button" onclick="add_image('19')">add</button><input type="file" id='id_image' name='image19' /></div>
                <div><button type="button" onclick="add_image('20')">add</button><input type="file" id='id_image' name='image20' /></div> 
                <div><button type="button" onclick="add_image('21')">add</button><input type="file" id='id_image' name='image21' /></div>
                <div><button type="button" onclick="add_image('22')">add</button><input type="file" id='id_image' name='image22' /></div> 
                <div><button type="button" onclick="add_image('23')">add</button><input type="file" id='id_image' name='image23' /></div>
                <div><button type="button" onclick="add_image('24')">add</button><input type="file" id='id_image' name='image24' /> </div>
                <div><button type="button" onclick="add_image('25')">add</button><input type="file" id='id_image' name='image25' /></div>
                <div><button type="button" onclick="add_image('26')">add</button><input type="file" id='id_image' name='image26' /> </div>
                <div><button type="button" onclick="add_image('27')">add</button><input type="file" id='id_image' name='image27' /> </div>
                <div><button type="button" onclick="add_image('28')">add</button><input type="file" id='id_image' name='image28' /></div> 
                <div><button type="button" onclick="add_image('29')">add</button><input type="file" id='id_image' name='image29' /></div>
                <div><button type="button" onclick="add_image('30')">add</button><input type="file" id='id_image' name='image30' /></div> 
                <div><button type="button" onclick="add_image('31')">add</button><input type="file" id='id_image' name='image31' /></div>
                <div><button type="button" onclick="add_image('32')">add</button><input type="file" id='id_image' name='image32' /></div> 
                <div><button type="button" onclick="add_image('33')">add</button><input type="file" id='id_image' name='image33' /></div>
                <div><button type="button" onclick="add_image('34')">add</button><input type="file" id='id_image' name='image34' /></div>
                <div><button type="button" onclick="add_image('35')">add</button><input type="file" id='id_image' name='image35' /></div>
            </div>



<button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

user/templates/user/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>





 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'user/main.css'%}">






{%if title%}
<title>{{title}}</title>
{%else%}
<title>django-app</title>
{%endif%}
</head>
<body>












<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
    
     {%if messages%}
     	{%for message in messages%}
     	 <div class="alert alert-{{ message.tags }}">
     	  {{ message }}
     	 </div>
     	{%endfor%}
      
     {%endif%}
    
    
      {% block content %}{% endblock %}
    </div>
    </div>
  </div>
</main>






<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>

user/templates/user/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'user/main.css'%}">
    <title>Document</title>
</head>
<body>
    
{% load crispy_forms_tags %}
{%if not user.is_authenticated%}
<br><br>


<main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        <div class="content-section" >

            <form method="POST">
                {% csrf_token %}
        
                <fieldset class="form-group">
                <legend class="border-bottom mb-4">SIGN IN</legend>
                {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                <button class="btn-outline-info">
                LOG IN
                </button>
        
                </div>
        
            </form>
        
            <div class="border-top pt-3"></div>
            <small class="text-muted">If you don't have an account then sign up !!!
            <a href="{%url 'register'%}" class="ml-2">SIGN UP</a><br>
            <a href="{%url 'home_page'%}" class="ml-2">Back to Home</a>
            </small>
        
        
        </div>
        {%endif%}
       
      </div>
      </div>
    </div>
  </main>

</body>
</html>

user/templates/user/logout.html
<h2>YOU HAVE BEEN LOGGED OUT</h2>
<div class="border-top pt-3">
 <small class="text-muted">Please log in
  <a href="{%url 'login'%}" >Log in again</a>
 </small>
</div>

user/templates/user/register.html
{%load static%}
<!DOCTYPE html>
<html>
<head>





 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{%static 'user/main.css'%}">






{%if title%}
<title>{{title}}</title>
{%else%}
<title>django-app</title>
{%endif%}
</head>
<body>








{%if not user.is_authenticated%}



<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
        {% load crispy_forms_tags %}
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Join Today</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Sign Up</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{%url 'login'%}">Sign In</a><br>
                    <a href="{%url 'home_page'%}" class="ml-2">Back to Home</a>
                </small>
            </div>
        </div>
    </div>
    </div>
  </div>
</main>

{%endif%}




<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>